Nh simple sentences
nxnode/Code-Challenges pull request #13
Opened 2022-09-13 00:25 UTC by nxnode

finished another code wars and created a merge conflict with the README

2022-09-13 16:01 UTC, W-Ely requested changes
The only change you really need to make here is the `sentence_parts` variable name to be singular.

The rest is food for thought.

If I make some assumption based on the instructions (which we know could be wrong):
```
Implement a function, so it will produce a sentence out of the given parts.

Array of parts could contain:

words;
commas in the middle;
multiple periods at the end.
Sentence making rules:

there must always be a space between words;
there must not be a space between a comma and word on the left;
there must always be one and only one period at the end of a sentence.
```

I would say that we can expect every string in the list to be either a word or a comma up to the end of the list, so really only 3 conditions are needed.  Is the part a comma, a period, or anything else. Then handle each one accordingly to construct the sentence.

Something like:
```python
 def make_sentences(parts):
    sentence = ""
    for part in parts:
        if part == ",":
            """Handle adding a `, `, and potentially removing the existing trailing space. Consider `rstrip`"""
        elif part == ".":
            """Handle adding a `.`, or defer this for later by breaking out"""
        else:
            """Handle adding the word and a space to the sentence
    """fix the sentence by removing extra space adding a period"""
    return sentence
 ``` 
 
 
 [rstrip](https://docs.python.org/3/library/stdtypes.html#str.rstrip)

2022-09-13 16:01 UTC, W-Ely commented on code_challenges/code_wars/simple_sentences.py
> +    for i, sentence_parts in enumerate(words):
In theory each iteration is a single sentence part, either a word, comma, or period.  So should be singular, `sentence_part`.

2022-09-13 16:01 UTC, W-Ely commented on code_challenges/code_wars/simple_sentences.py
> +            i += 1
It is unconventional to increment the `i` inside the for loop.  Each iteration resets this to the count that enumerate is providing.  You might be relying on this count being higher than the loop makes it in the last if statement, if so that could be handled there instead of incrementing in every if/else path.

2022-09-13 16:01 UTC, W-Ely commented on code_challenges/code_wars/simple_sentences.py
> +            if sentence_parts in punctuation:
Frequently when you have an
```python
else:
    if ...
```
You should consider if the `elif` condition would simplify the indentation logic.

2022-09-14 18:28 UTC, nxnode commented
I wondered about elif's and I wasn't sure if there was a reason to go one way or the other. At first I actually thought it wouldn't make much of a difference with it's readability but you knew. The same thing (or close to the same thing) is much easier to follow with elif.

2022-09-14 18:28 UTC, W-Ely approved these changes

2022-09-19 22:20 UTC, merged